### ISSUE TITLE
Bourne et al. 2007 inconsistency.

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#14]
Bourne et al. 2007 -- humerus: 
Detected ISB oriented: False 
Detected ISB origin: True Humerus.GLENOHUMERAL_HEAD Detected ISB oriented + origin: False 
Expected: True

**Comment by fmoissenet** [comment]
Error on Humerus_Y definition: -anteroposterior instead of +anteroposterior
Comments:
- this issue might be generalised on many rows of the table
- it would make sense to replace -anteroposterior by +posteroanterior

**Comment by ANaaim** [comment]
I do not agree on -anteroposterior, I am ok with +posteroanterior.

**Comment by Ipuch** [comment]
The conversation on this debate has been displaced in #42. Since Bourne et al. 2007 article doesn't exist anymore, this issue is not even relevant, see #22.
