### ISSUE TITLE
Inconsistency Dal Maso et al. 2014

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#15]
Dal Maso et al. 2014 -- scapula: 
Detected ISB oriented: True 
Detected ISB origin: True Scapula.ANGULAR_ACROMIALIS Detected ISB oriented + origin: True 

- [x] removed from sharepoint
- [x] removed from github .csv
- [x] removed from github data

**Comment by fmoissenet** [comment]
Article removed from list.
This issue can be closed.
