### ISSUE TITLE
Inconsistency Cereatti et al. 2017

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#16]
Cereatti et al. 2017 -- scapula: 
Detected ISB oriented: True 
Detected ISB origin: True Scapula.ANGULAR_ACROMIALIS Detected ISB oriented + origin: True 
Expected: False

**Comment by ANaaim** [comment]
The article has disapear.  I suppose we are not using it anymore.

**Comment by Ipuch** [comment]
Yes, after checking myself, the four rows (2 DalMaso, 2 Charbonnier). No row has a scapula with excepted is_isb to False.
