### ISSUE TITLE
Inconsistency Graichen et al. 2000, check is isb_like from its initial definition

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#17]
Graichen et al. 2000 -- humerus: 
Detected ISB oriented: True 
Detected ISB origin: True Humerus.GLENOHUMERAL_HEAD 
Detected ISB oriented + origin: True 
Expected: False 

- [x] Tableau
- [x] Pushed

**Comment by fmoissenet** [comment]
I was not able to find again the humerus axes definitions in the paper, but I guess that +anteroposterior (Humerus_X) should be replaced by -anteroposterior.

**Comment by Ipuch** [comment]
-> Test to add verify if everything ISB but not is_isb then correctable == false and no correction available. 
This is a is_isb_like from the beginning.

**Comment by Ipuch** [comment]
Anyway, we don't care since the humerothoracic angle is driven by an operator and not computed from rotation matrices.
