### ISSUE TITLE
Inconsistency Guttierrez

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#18]
Gutierrez Delgado et al. 2017 -- clavicle: 
Detected ISB oriented: True 
Detected ISB origin: True Clavicle.STERNOCLAVICULAR_JOINT_CENTER 
Detected ISB oriented + origin: True 
Expected: False

- [x] Tableau
- [x] Pushed

**Comment by fmoissenet** [comment]
Clavicle_X definition: +anteroposterior should be replaced by -anteroposterior.

**Comment by ANaaim** [comment]
@fmoissenet  : I do not understand, iin the article the X  clavicle axis is pointinng forward... it should then be +antero-posterior ?

**Comment by ANaaim** [comment]
I have put back +anteroposterior instead of -anteroposterior sur Guterriez Delgado

**Comment by Ipuch** [comment]
@ANaaim and @fmoissenet, Is it a ISB = True, or is it isb like ?
