### ISSUE TITLE
Inconsistency Ludwig et al. 2009

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#19]
Ludewig et al. 2009 -- thorax: 
Detected ISB oriented: True 
Detected ISB origin: True Thorax.IJ 
Detected ISB oriented + origin: True 
Expected: False 

- [x] Tableau
- [ ] Pushed

**Comment by ANaaim** [comment]
Data in the table are correct. The thorax is oriented using the global frame.  of the You should add in the test for the thorax to verify if the thorax is not oriented globally.
