### ISSUE TITLE
Inconcistency McClure 2001

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#20]
McClure et al. 2001 -- scapula: 
Detected ISB oriented: False 
Detected ISB origin: False Scapula.TRIGNONUM_SPINAE Detected ISB oriented + origin: False 
Expected: True 

- [x] Tableau
- [x] Pushed

**Comment by fmoissenet** [comment]
Again I wondering if there is not an issue (in many data) between +anteroposterior and -anteroposterior to define an axis going from posterior to anterior ... to be changed in table is needed

**Comment by ANaaim** [comment]
In the article the mediolateral axis(X axis in the article) go from TS to AC which is not ISB. 
X : +medio lat (from TS to AC)

Scapula: AC, acromioclavicular joint; SP, root of scapular
spine; IA, inferior angle; 
XS :  vector connecting SP to AC; = +mediolat
YS : vector perpendicular to plane AC-SP-IA; = +anteroposterio  
ZS : cross product of XS and YS. = +inferosup

Change done in the table : Scapula_is_ISB go from true to false

**Comment by Ipuch** [comment]
Thanks @ANaaim ! Just an update of .csv file is required to close the issue :+1:
