### ISSUE TITLE
Add Data Bourne 2004

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#22]
Add the data of the Master Thesis of Bourne
- [x] Engauge
- [x] Data on git
- [x] Tableau on sharepoint
- [x] Deleting on the tableau sharepoint of Bourne et al. 2007 I guess  @fmoissenet 
- [x] Deleting the data of Bourne et al. 2007 I guess  @fmoissenet 
- [x] 2004 to 2003

**Comment by Ipuch** [comment]
Let's close issues when the we merge the modifications:)

**Comment by Ipuch** [comment]
Okay, you actually directly pushed everything through my main branch.
Nothing wrong happened ;) I fixed everything! 

Here is the workflow, you should have:

- The repository should be forked
- Your main branch should always be at the same commit as my main
- New commit should be pushed on a dedicated parallel branch
- Then Open a pull request from you branch to my main branch

We will review the process during the next meeting :+1:

**Comment by Ipuch** [comment]
Wait I forgot this should be added to .csv file now I guess.

**Comment by fmoissenet** [comment]
This issue can be closed
