### ISSUE TITLE
Update Gutierrez Delgado et al data

### ISSUE THREAD

**Issue by fmoissenet** [Ipuch/shoulder-kinematic-dataset#30]
Engauge data replaced by author data
New CSV currently on Florent computer > To be transferred
- [x] on my local computer
- [x] data added on github
- [x] Sharepoint extraction table updated
- [x] .csv file updated

**Comment by fmoissenet** [comment]
Extraction table updated accordingly

**Comment by Ipuch** [comment]
- [ ] data added
- [ ] .csv file updated
