### ISSUE TITLE
Remove Zhang et al. data

### ISSUE THREAD

**Issue by fmoissenet** [Ipuch/shoulder-kinematic-dataset#47]
- [x] Sharepoint extraction table updated
- [x] data on git (pull request)
- [x] update .csv on github

**Comment by Ipuch** [comment]
Can we just write in one sentence why we don't keep this data ?

**Comment by fmoissenet** [comment]
Dataset not used as results are expressed as a function of glenohumeral joint angle and not thoracohumeral joint angle. No raw data provided by authors to recompute thoracohumeral joint angle.
