### ISSUE TITLE
Bourne 2003 inconsistency.

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#48]
row_data.joint Bourne 2003
Bourne 2003, Segment scapula is not direct. It should be.
Please still consider anteropost axis as pointing forward, as #42 is not treated yet.

**Comment by Ipuch** [comment]
@fmoissenet

**Comment by fmoissenet** [comment]
I confirm that the scapula coordinate system is direct. Extraction table corrected accordingly (-mediolateral > +mediolateral).
![image](https://github.com/Ipuch/shoulder-kinematic-dataset/assets/14890048/3c10186c-3e7a-4eb3-8cea-b7afb788f696)
