### ISSUE TITLE
[RTC] Ludewig et al. 2009 

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#54]
- [x] Sharepoint extraction table updated
- [x] data on git (pull request)
- [x] update .csv on github

This is my error message: 
> row_data.joint Ludewig et al. 2009
> WARNING : inconsistency in the dataset
> --  Ludewig et al. 2009  --
> Segment.THORAX
> detected ISB oriented: True
> detected ISB origin: True Thorax.IJ
> detected ISB oriented + origin: True
> expected ISB: False

The frame is reported as not isb, but global, all the data suggest it is isb. 

1. Does the origin IJ justified if the frame is global ?
2. Is it an ISB like by its original definition, if so I should rely on correctable = False to determine it as mentioned in #44.

Could please check on this ?

**Comment by fmoissenet** [comment]
Actually, our interpretation of the paper might not be good. The dataset is the same than in Lawrence et al. 2014, where the thorax (as other segments) is defined ISB. The authors also confirm in their answer that only scapula does not follow ISB recommendations for coordinate system definition.
