### ISSUE TITLE
[RTC] Matsuki et al. 2012

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#56]
This is the error message:

> row_data.joint Matsuki et al. 2012
> ['thorax_x', 'thorax_y', 'thorax_z', 'thorax_origin']  is filled with nan
> ['clavicle_x', 'clavicle_y', 'clavicle_z', 'clavicle_origin']  is filled with nan
> Joint glenohumeral has no correction value in the parent segment scapula, it should be filled with a Correction.TO_ISB_ROTATION, because the segment is not isb. Current value: []
> Joint glenohumeral has no correction value in the parent segment scapula, it should be filled with a Correction.TO_ISB_LIKE_ROTATION correction, because the segment is not isb. Current value: []
> WARNING : No usable data for this row, in both rotation and translation...

The scapula frame is reported not isb, and it is indeed not isb. but no correction is provided, we should at least have to_isb_like correction.
Please correct this :)

**Comment by ANaaim** [comment]
Modification have been done on the excel and the associated pull request done

**Comment by Ipuch** [comment]
Also, we set the thoracohumeral angle angle(yh,yt), instead of the mistaken Euler sequence.
