### ISSUE TITLE
[RTC] Mastuki et al. 2014

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#57]
This is the error message: 

> Joint sternoclavicular has a NaN value in the parent segment thorax, it should not be empty !!!

The problem is in the thorax segment; we know it's a global frame, not ISB, and not correctable. But we don't even know the orientation of the axes of the global coordinate system. I need it in order to verify we haven't missed any corrections, such as to_isb_like.

Please let me know if we can get it.

**Comment by ANaaim** [comment]
There is no clear definition of the frame of the thorax. One solution would be to assume that as the ISB sequences is used for the angle calculation, we could say the axis are globally oriented as the ISB recommend. 
However when we go to the article cited https://www.sciencedirect.com/science/article/pii/S105827461000412X#bib12
==> they do not use ISB definition.... ...

Question why we did not used this artcile from the same team ? (are the data the same as the one in matsuki 2012)

**Comment by Ipuch** [comment]
We set the thoracohumeral angle angle(yh,yt), instead of the mistaken euler sequence.
