### ISSUE TITLE
Extra check on the order of corrections.

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/shoulder-kinematic-dataset#63]
When more than two correction methods are specified for a segment. We should care about the order:

We could have this case with scapula:

- to_isb_like, first we set the axis in the biomechanical directions
- kolz_GC_to_PA, once we have a proper coordinate system, we can apply this correction.

But the opposite makes no sense.

**Comment by ANaaim** [comment]
There is currently no cases where the methode kolz is written before the méthode to_isb_like in the excel document.
